// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import path from "path";

const dbDir = process.env.RAILWAY_VOLUME_MOUNT_PATH || process.cwd();
const dbUrl = `file:${path.join(dbDir, "dev.db")}`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] || dbUrl,
  },
});
